# LEGO DATA ANALYSIS: REBRICKABLE

In [6]:
#import liberaries

import pandas as pd
import numpy as np

getting data

In [41]:
sets= pd.read_csv(r"C:\Users\HP\Desktop\DATASET\Rebrickable datasource\LEGO\sets.csv")
sets

,set_num,name,year,theme_id,num_parts,img_url
0,0003977811-1,Ninjago: Book of Adventures,2022,761,1,https://cdn.rebrickable.com/media/sets/0003977...
1,001-1,Gears,1965,756,43,https://cdn.rebrickable.com/media/sets/001-1.jpg
2,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg
3,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg
4,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg
...,...,...,...,...,...,...
22701,XWING-1,Mini X-Wing Fighter,2019,158,60,https://cdn.rebrickable.com/media/sets/xwing-1...
22702,XWING-2,X-Wing Trench Run,2019,158,52,https://cdn.rebrickable.com/media/sets/xwing-2...
22703,YODACHRON-1,Yoda Chronicles Promotional Set,2013,158,413,https://cdn.rebrickable.com/media/sets/yodachr...
22704,YTERRIER-1,Yorkshire Terrier,2018,598,0,https://cdn.rebrickable.com/media/sets/yterrie...
22705,ZX8000-1,ZX 8000 LEGO Sneaker,2020,501,0,https://cdn.rebrickable.com/media/sets/zx8000-...

In [42]:
themes= pd.read_csv(r"C:\Users\HP\Desktop\DATASET\Rebrickable datasource\LEGO\themes.csv")
themes

      id                            name  parent_id
0      1                         Technic        NaN
1      3                     Competition        1.0
2      4                  Expert Builder        1.0
3     16                      RoboRiders        1.0
4     17                  Speed Slammers        1.0
..   ...                             ...        ...
456  759                     Story Books      497.0
457  760                  Activity Books      497.0
458  761  Activity Books with LEGO Parts      497.0
459  762           Series 26 Minifigures      535.0
460  763                 Despicable Me 4        NaN

[461 rows x 3 columns]

Top 10 rows of the sets dataset

In [43]:
sets.head(10)

,set_num,name,year,theme_id,num_parts,img_url
0,0003977811-1,Ninjago: Book of Adventures,2022,761,1,https://cdn.rebrickable.com/media/sets/0003977...
1,001-1,Gears,1965,756,43,https://cdn.rebrickable.com/media/sets/001-1.jpg
2,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg
3,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg
4,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg
5,0013-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0013-1.jpg
6,0014-1,Space Mini-Figures,1979,143,2,https://cdn.rebrickable.com/media/sets/0014-1.jpg
7,0015-1,Space Mini-Figures,1979,143,18,https://cdn.rebrickable.com/media/sets/0015-1.jpg
8,0016-1,Castle Mini Figures,1979,189,15,https://cdn.rebrickable.com/media/sets/0016-1.jpg
9,002-1,4.5V Samsonite Gears Motor Set,1965,756,3,https://cdn.rebrickable.com/media/sets/002-1.jpg

lowest 10 of the sets dataset

In [44]:
sets.tail(10)

,set_num,name,year,theme_id,num_parts,img_url
22696,XBOXGAME-1,Batman the Videogame - Xbox 360,2008,742,0,https://cdn.rebrickable.com/media/sets/xboxgam...
22697,XBOXGAME-2,Bionicle Heroes - Xbox 360,2006,742,0,https://cdn.rebrickable.com/media/sets/xboxgam...
22698,XBOXGAME-3,DC Super-Villains - Xbox One,2018,742,0,https://cdn.rebrickable.com/media/sets/xboxgam...
22699,XBOXGAME-9,Star Wars: The Video Game - Xbox,2005,742,0,https://cdn.rebrickable.com/media/sets/xboxgam...
22700,XMASTREE-1,Christmas Tree,2019,410,26,https://cdn.rebrickable.com/media/sets/xmastre...
22701,XWING-1,Mini X-Wing Fighter,2019,158,60,https://cdn.rebrickable.com/media/sets/xwing-1...
22702,XWING-2,X-Wing Trench Run,2019,158,52,https://cdn.rebrickable.com/media/sets/xwing-2...
22703,YODACHRON-1,Yoda Chronicles Promotional Set,2013,158,413,https://cdn.rebrickable.com/media/sets/yodachr...
22704,YTERRIER-1,Yorkshire Terrier,2018,598,0,https://cdn.rebrickable.com/media/sets/yterrie...
22705,ZX8000-1,ZX 8000 LEGO Sneaker,2020,501,0,https://cdn.rebrickable.com/media/sets/zx8000-...

check datatypes of each column

In [18]:
sets.dtypes

set_num      object
name         object
year          int64
theme_id      int64
num_parts     int64
img_url      object
dtype: object

check NULL values in sets dataset

In [20]:
sets.isnull().sum()

set_num      0
name         0
year         0
theme_id     0
num_parts    0
img_url      0
dtype: int64

In [45]:
themes.isnull().sum()

id             0
name           0
parent_id    138
dtype: int64

How many roles and columns in our dataset

In [26]:
sets.shape

(22706, 6)

In [28]:
len(sets.columns)

6

In [29]:
len(sets)

22706

In [38]:
sets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22706 entries, 0 to 22705
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   set_num    22706 non-null  object
 1   name       22706 non-null  object
 2   year       22706 non-null  int64
 3   theme_id   22706 non-null  int64
 4   num_parts  22706 non-null  int64
 5   img_url    22706 non-null  object
dtypes: int64(3), object(3)
memory usage: 1.0+ MB

# MERGE DATA

Joining the 2 dataset to answer questions

In [48]:
sets_themes=pd.merge(sets,themes, how = 'left' , left_on = 'theme_id', right_on ='id', suffixes = ('_sets','_themes'))
sets_themes

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id
0,0003977811-1,Ninjago: Book of Adventures,2022,761,1,https://cdn.rebrickable.com/media/sets/0003977...,761,Activity Books with LEGO Parts,497.0
1,001-1,Gears,1965,756,43,https://cdn.rebrickable.com/media/sets/001-1.jpg,756,Samsonite,365.0
2,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg,67,Classic Town,50.0
3,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg,199,Lion Knights,186.0
4,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg,143,Supplemental,126.0
...,...,...,...,...,...,...,...,...,...
22701,XWING-1,Mini X-Wing Fighter,2019,158,60,https://cdn.rebrickable.com/media/sets/xwing-1...,158,Star Wars,NaN
22702,XWING-2,X-Wing Trench Run,2019,158,52,https://cdn.rebrickable.com/media/sets/xwing-2...,158,Star Wars,NaN
22703,YODACHRON-1,Yoda Chronicles Promotional Set,2013,158,413,https://cdn.rebrickable.com/media/sets/yodachr...,158,Star Wars,NaN
22704,YTERRIER-1,Yorkshire Terrier,2018,598,0,https://cdn.rebrickable.com/media/sets/yterrie...,598,Promotional,NaN
22705,ZX8000-1,ZX 8000 LEGO Sneaker,2020,501,0,https://cdn.rebrickable.com/media/sets/zx8000-...,501,Gear,NaN

In [49]:
sets_themes.head()

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id
0,0003977811-1,Ninjago: Book of Adventures,2022,761,1,https://cdn.rebrickable.com/media/sets/0003977...,761,Activity Books with LEGO Parts,497.0
1,001-1,Gears,1965,756,43,https://cdn.rebrickable.com/media/sets/001-1.jpg,756,Samsonite,365.0
2,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg,67,Classic Town,50.0
3,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg,199,Lion Knights,186.0
4,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg,143,Supplemental,126.0

In [50]:
sets_themes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22706 entries, 0 to 22705
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   set_num      22706 non-null  object
 1   name_sets    22706 non-null  object
 2   year         22706 non-null  int64
 3   theme_id     22706 non-null  int64
 4   num_parts    22706 non-null  int64
 5   img_url      22706 non-null  object
 6   id           22706 non-null  int64
 7   name_themes  22706 non-null  object
 8   parent_id    13307 non-null  float64
dtypes: float64(1), int64(4), object(4)
memory usage: 1.7+ MB

In [52]:
sets_themes.columns

Index(['set_num', 'name_sets', 'year', 'theme_id', 'num_parts', 'img_url',
       'id', 'name_themes', 'parent_id'],
      dtype='object')

## Lets answer some questions

1) whats the total numbers of parts per theme

In [63]:
Num_Parts_per_Themes=sets_themes.groupby('name_themes').sum().reset_index()
Num_Parts_per_Themes=Num_Parts_per_Themes[['name_themes','num_parts']].sort_values('num_parts' , ascending = False)
Num_Parts_per_Themes

                     name_themes  num_parts
333                      Technic     265633
317                    Star Wars     254243
123                      Friends     134880
222                      Ninjago     125292
154                        Icons     110743
..                           ...        ...
242       Posters and Art Prints          0
240                   Plush Toys          0
5                 Activity Books          0
261  Role Play Toys and Costumes          0
27          Bag and Luggage Tags          0

[388 rows x 2 columns]

2) whats the total number of parts per year

In [64]:
Num_Parts_per_Year=sets_themes.groupby('year').sum().reset_index()
Num_Parts_per_Year=Num_Parts_per_Year[['year','num_parts']].sort_values('num_parts' , ascending = False)
Num_Parts_per_Year

    year  num_parts
72  2023     300887
71  2022     281277
70  2021     265432
69  2020     212104
68  2019     192623
..   ...        ...
3   1954        117
8   1959         57
2   1953         50
1   1950          6
74  2025          0

[75 rows x 2 columns]

3) How many sets were created in each century in the dataset

we have to create century as a derived column to the sets_themes dataset

In [69]:
unique_year=sets_themes['year'].unique()
unique_year.sort()
unique_year

array([1949, 1950, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961,
       1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
       1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983,
       1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025], dtype=int64)

In [75]:
sets_themes['year'] > 2000
sets_themes['century']= np.where(sets_themes['year'] > 2000,'21st_century', '20th_century')
sets_themes

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id,century
0,0003977811-1,Ninjago: Book of Adventures,2022,761,1,https://cdn.rebrickable.com/media/sets/0003977...,761,Activity Books with LEGO Parts,497.0,21st_century
1,001-1,Gears,1965,756,43,https://cdn.rebrickable.com/media/sets/001-1.jpg,756,Samsonite,365.0,20th_century
2,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg,67,Classic Town,50.0,20th_century
3,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg,199,Lion Knights,186.0,20th_century
4,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg,143,Supplemental,126.0,20th_century
...,...,...,...,...,...,...,...,...,...,...
22701,XWING-1,Mini X-Wing Fighter,2019,158,60,https://cdn.rebrickable.com/media/sets/xwing-1...,158,Star Wars,NaN,21st_century
22702,XWING-2,X-Wing Trench Run,2019,158,52,https://cdn.rebrickable.com/media/sets/xwing-2...,158,Star Wars,NaN,21st_century
22703,YODACHRON-1,Yoda Chronicles Promotional Set,2013,158,413,https://cdn.rebrickable.com/media/sets/yodachr...,158,Star Wars,NaN,21st_century
22704,YTERRIER-1,Yorkshire Terrier,2018,598,0,https://cdn.rebrickable.com/media/sets/yterrie...,598,Promotional,NaN,21st_century
22705,ZX8000-1,ZX 8000 LEGO Sneaker,2020,501,0,https://cdn.rebrickable.com/media/sets/zx8000-...,501,Gear,NaN,21st_century

In [76]:
Num_set_per_century=sets_themes.groupby('century').count().reset_index()
Num_set_per_century[['century','set_num']]

        century  set_num
0  20th_century     5079
1  21st_century    17627

4) What percentage of sets ever released in 21 century were Trains themes

In [84]:
century_21st_data=sets_themes[sets_themes['century']== '21st_century']
Train=century_21st_data[century_21st_data['name_themes'].str.contains('Train')]

In [87]:
century_21st_data.shape[0]

17627

In [88]:
Train.shape[0]

68

In [90]:
Train.shape[0]/century_21st_data.shape[0] * 100

0.3857718273103761

5) What percentage of sets ever released in 21 century were Disney themes

In [92]:
Disney=century_21st_data[century_21st_data['name_themes'].str.contains('Disney')]
Disney

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id,century
474,10418-1,Elsa & Bruni in the Enchanted Forest,2024,640,31,https://cdn.rebrickable.com/media/sets/10418-1...,640,Disney Princess,754.0,21st_century
515,10515-1,Ariel's Undersea Castle,2013,640,39,https://cdn.rebrickable.com/media/sets/10515-1...,640,Disney Princess,754.0,21st_century
516,10516-1,Ariel's Magical Boat Ride,2012,640,30,https://cdn.rebrickable.com/media/sets/10516-1...,640,Disney Princess,754.0,21st_century
537,10542-1,Sleeping Beauty's Fairy Tale,2014,640,55,https://cdn.rebrickable.com/media/sets/10542-1...,640,Disney Princess,754.0,21st_century
584,10596-1,Disney Princess Collection,2015,640,63,https://cdn.rebrickable.com/media/sets/10596-1...,640,Disney Princess,754.0,21st_century
...,...,...,...,...,...,...,...,...,...,...
21376,BELLE-1,Belle's Castle,2016,579,72,https://cdn.rebrickable.com/media/sets/belle-1...,579,Disney Princess,608.0,21st_century
21457,CINDERELLASCASTLE-1,Cinderella's Castle,2017,608,102,https://cdn.rebrickable.com/media/sets/cindere...,608,Disney,NaN,21st_century
22464,ROSE-1,The Beast's Enchanted Rose,2017,608,19,https://cdn.rebrickable.com/media/sets/rose-1.jpg,608,Disney,NaN,21st_century
22601,TRUCOGSWORTH-1,Cogsworth,2016,608,48,https://cdn.rebrickable.com/media/sets/trucogs...,608,Disney,NaN,21st_century
22613,TRULUMIERE-1,Lumiere,2016,608,24,https://cdn.rebrickable.com/media/sets/trulumi...,608,Disney,NaN,21st_century

In [94]:
Disney.shape[0]

235

In [95]:
Disney.shape[0]/century_21st_data.shape[0] * 100

1.3331820502637999

6) What percentage of sets ever released in 21 century were star wars themes

In [96]:
star_war=century_21st_data[century_21st_data['name_themes'].str.contains('Star')]
star_war

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id,century
2188,20006-1,Clone Turbo Tank,2008,158,64,https://cdn.rebrickable.com/media/sets/20006-1...,158,Star Wars,NaN,21st_century
2199,20007-1,Republic Attack Cruiser,2009,158,84,https://cdn.rebrickable.com/media/sets/20007-1...,158,Star Wars,NaN,21st_century
2212,20009-1,AT-TE Walker,2009,158,94,https://cdn.rebrickable.com/media/sets/20009-1...,158,Star Wars,NaN,21st_century
2214,20010-1,Republic Gunship,2009,158,94,https://cdn.rebrickable.com/media/sets/20010-1...,158,Star Wars,NaN,21st_century
2222,20016-1,Imperial Shuttle,2010,158,70,https://cdn.rebrickable.com/media/sets/20016-1...,158,Star Wars,NaN,21st_century
...,...,...,...,...,...,...,...,...,...,...
22654,VP-10,Star Wars Value Pack with Free LEGO Backpack,2003,158,1,https://cdn.rebrickable.com/media/sets/vp-10.jpg,158,Star Wars,NaN,21st_century
22661,VP-2,Star Wars Co-Pack,2001,158,0,https://cdn.rebrickable.com/media/sets/vp-2.jpg,158,Star Wars,NaN,21st_century
22701,XWING-1,Mini X-Wing Fighter,2019,158,60,https://cdn.rebrickable.com/media/sets/xwing-1...,158,Star Wars,NaN,21st_century
22702,XWING-2,X-Wing Trench Run,2019,158,52,https://cdn.rebrickable.com/media/sets/xwing-2...,158,Star Wars,NaN,21st_century
22703,YODACHRON-1,Yoda Chronicles Promotional Set,2013,158,413,https://cdn.rebrickable.com/media/sets/yodachr...,158,Star Wars,NaN,21st_century

In [97]:
star_war.shape[0]

908

In [98]:
star_war.shape[0]/century_21st_data.shape[0] * 100

5.151188517615022

7) What percentage of sets ever released in 21 century were Gear themes

In [99]:
Gear=century_21st_data[century_21st_data['name_themes'].str.contains('Gear')]
Gear

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id,century
150,100291707-1,Ninjago Lloyd Backpack,2018,501,0,https://cdn.rebrickable.com/media/sets/1002917...,501,Gear,NaN,21st_century
151,100291708-1,Nexo Knights Backpack,2018,501,0,https://cdn.rebrickable.com/media/sets/1002917...,501,Gear,NaN,21st_century
153,100301705-1,Friends You're the Star Junior Backpack,2018,501,0,https://cdn.rebrickable.com/media/sets/1003017...,501,Gear,NaN,21st_century
154,100302304-1,Mermaid Junior Backpack,2023,501,0,https://cdn.rebrickable.com/media/sets/1003023...,501,Gear,NaN,21st_century
155,100311708-1,Nexo Knights Shoulder Bag,2018,501,0,https://cdn.rebrickable.com/media/sets/1003117...,501,Gear,NaN,21st_century
...,...,...,...,...,...,...,...,...,...,...
22651,VIPPACKAGE-1,Harry Potter: Special Starter Pack,2023,501,1,https://cdn.rebrickable.com/media/sets/vippack...,501,Gear,NaN,21st_century
22652,VISION-1,Vision Photo Signed by Paul Bettany,2021,501,0,https://cdn.rebrickable.com/media/sets/vision-...,501,Gear,NaN,21st_century
22671,WALLET-1,Minifigure Emoji Wallet (Blue),2020,501,0,https://cdn.rebrickable.com/media/sets/wallet-...,501,Gear,NaN,21st_century
22672,WALLET-3,Ninjago Wallet,2019,501,0,https://cdn.rebrickable.com/media/sets/wallet-...,501,Gear,NaN,21st_century
22705,ZX8000-1,ZX 8000 LEGO Sneaker,2020,501,0,https://cdn.rebrickable.com/media/sets/zx8000-...,501,Gear,NaN,21st_century

In [100]:
Gear.shape[0]

623

In [101]:
Gear.shape[0]/century_21st_data.shape[0] * 100

3.534350711975946

8) whats the popular themes by year in term of set released in 21 century

In [109]:
Popular_Theme_per_Year=century_21st_data.groupby (['year','name_themes']).count().reset_index()
Popular_Theme_per_Year=Popular_Theme_per_Year[['year','name_themes','set_num']].sort_values('set_num', ascending = False)
Popular_Theme_per_Year.drop_duplicates('year').sort_values('year', ascending = False)

      year                     name_themes  set_num
1924  2025  Activity Books with LEGO Parts        1
1899  2024                         Ninjago       34
1798  2023                            Gear       55
1709  2022                            Gear       60
1620  2021                            Gear      156
1526  2020                         Friends       59
1484  2019               The LEGO Movie II       64
1383  2018                       Star Wars       69
1293  2017                       Star Wars       64
1204  2016                       Star Wars       63
1100  2015                       Star Wars       69
1004  2014                         Technic      118
903   2013                       Star Wars       41
785   2012                         Ninjago       47
702   2011                         Ninjago       43
616   2010                       Key Chain       44
568   2009                       Star Wars       35
445   2008                        Bionicle       39
403   2007                       Key Chain       36
314   2006                        Bionicle       50
248   2005                        Bionicle       38
188   2004                        Bionicle       51
123   2003                        Bionicle       63
109   2002                         Technic       64
7     2001                        Bionicle       45

9) whats the most produced color of LEGO in term of quantity of parts

Note: Joining two(2) dataset to answer question

In [118]:
colors=pd.read_csv(r"C:\Users\HP\Desktop\DATASET\Rebrickable datasource\LEGO\colors.csv")
colors

       id                  name     rgb is_trans
0      -1             [Unknown]  0033B2        f
1       0                 Black  05131D        f
2       1                  Blue  0055BF        f
3       2                 Green  237841        f
4       3        Dark Turquoise  008F9B        f
..    ...                   ...     ...      ...
262  1136        Reddish Orange  CA4C0B        f
263  1137          Sienna Brown  915C3C        f
264  1138           Umber Brown  5E3F33        f
265  1139     Trans-Yellow Opal  F5CD2F        t
266  9999  [No Color/Any Color]  05131D        f

[267 rows x 4 columns]

In [112]:
inventory_parts=pd.read_csv(r"C:\Users\HP\Desktop\DATASET\Rebrickable datasource\LEGO\inventory_parts.csv")
inventory_parts

,inventory_id,part_num,color_id,quantity,is_spare,img_url
0,1,48379c04,72,1,f,https://cdn.rebrickable.com/media/parts/photos...
1,1,48395,7,1,f,https://cdn.rebrickable.com/media/parts/photos...
2,1,stickerupn0077,9999,1,f,NaN
3,1,upn0342,0,1,f,https://cdn.rebrickable.com/media/parts/photos...
4,1,upn0350,25,1,f,NaN
...,...,...,...,...,...,...
1239005,222802,6141,72,4,f,https://cdn.rebrickable.com/media/parts/elemen...
1239006,222802,6141,182,4,f,https://cdn.rebrickable.com/media/parts/elemen...
1239007,222802,63864,15,1,f,https://cdn.rebrickable.com/media/parts/elemen...
1239008,222802,63868,71,4,f,https://cdn.rebrickable.com/media/parts/elemen...
1239009,222802,99781,28,1,f,https://cdn.rebrickable.com/media/parts/elemen...

In [120]:
color_inventory=pd.merge(inventory_parts, colors, how = 'left', left_on = 'color_id', right_on = 'id')
color_inventory

,inventory_id,part_num,color_id,quantity,is_spare,img_url,id,name,rgb,is_trans
0,1,48379c04,72,1,f,https://cdn.rebrickable.com/media/parts/photos...,72,Dark Bluish Gray,6C6E68,f
1,1,48395,7,1,f,https://cdn.rebrickable.com/media/parts/photos...,7,Light Gray,9BA19D,f
2,1,stickerupn0077,9999,1,f,NaN,9999,[No Color/Any Color],05131D,f
3,1,upn0342,0,1,f,https://cdn.rebrickable.com/media/parts/photos...,0,Black,05131D,f
4,1,upn0350,25,1,f,NaN,25,Orange,FE8A18,f
...,...,...,...,...,...,...,...,...,...,...
1239005,222802,6141,72,4,f,https://cdn.rebrickable.com/media/parts/elemen...,72,Dark Bluish Gray,6C6E68,f
1239006,222802,6141,182,4,f,https://cdn.rebrickable.com/media/parts/elemen...,182,Trans-Orange,F08F1C,t
1239007,222802,63864,15,1,f,https://cdn.rebrickable.com/media/parts/elemen...,15,White,FFFFFF,f
1239008,222802,63868,71,4,f,https://cdn.rebrickable.com/media/parts/elemen...,71,Light Bluish Gray,A0A5A9,f
1239009,222802,99781,28,1,f,https://cdn.rebrickable.com/media/parts/elemen...,28,Dark Tan,958A73,f

In [125]:
color_inventory.rename(columns={'name':'color_name'}, inplace = True)
color_inventory

,inventory_id,part_num,color_id,quantity,is_spare,img_url,id,color_name,rgb,is_trans
0,1,48379c04,72,1,f,https://cdn.rebrickable.com/media/parts/photos...,72,Dark Bluish Gray,6C6E68,f
1,1,48395,7,1,f,https://cdn.rebrickable.com/media/parts/photos...,7,Light Gray,9BA19D,f
2,1,stickerupn0077,9999,1,f,NaN,9999,[No Color/Any Color],05131D,f
3,1,upn0342,0,1,f,https://cdn.rebrickable.com/media/parts/photos...,0,Black,05131D,f
4,1,upn0350,25,1,f,NaN,25,Orange,FE8A18,f
...,...,...,...,...,...,...,...,...,...,...
1239005,222802,6141,72,4,f,https://cdn.rebrickable.com/media/parts/elemen...,72,Dark Bluish Gray,6C6E68,f
1239006,222802,6141,182,4,f,https://cdn.rebrickable.com/media/parts/elemen...,182,Trans-Orange,F08F1C,t
1239007,222802,63864,15,1,f,https://cdn.rebrickable.com/media/parts/elemen...,15,White,FFFFFF,f
1239008,222802,63868,71,4,f,https://cdn.rebrickable.com/media/parts/elemen...,71,Light Bluish Gray,A0A5A9,f
1239009,222802,99781,28,1,f,https://cdn.rebrickable.com/media/parts/elemen...,28,Dark Tan,958A73,f

In [131]:
popular_color=color_inventory.groupby('color_name').sum().reset_index()
popular_color=popular_color[['color_name','quantity']].sort_values('quantity', ascending = False)
popular_color.head(50)

               color_name  quantity
1                   Black    775551
98      Light Bluish Gray    476378
250                 White    465885
25       Dark Bluish Gray    337788
181                   Red    302565
2                    Blue    202633
251                Yellow    202187
200                   Tan    161188
182         Reddish Brown    140363
100            Light Gray    105632
63                  Green     78337
34               Dark Tan     53036
162                Orange     46637
206           Trans-Clear     45648
23              Dark Blue     44958
169            Pearl Gold     44081
33               Dark Red     43174
113                  Lime     39491
216      Trans-Light Blue     30973
124         Medium Nougat     28535
27              Dark Gray     24692
5     Bright Light Orange     24646
231             Trans-Red     23130
50            Flat Silver     22645
116          Medium Azure     21659
191            Sand Green     20858
3            Bright Green     20717
28             Dark Green     19311
26             Dark Brown     18989
35         Dark Turquoise     18551
30            Dark Orange     18433
227          Trans-Orange     16112
32            Dark Purple     14807
233          Trans-Yellow     14757
7             Bright Pink     14670
117           Medium Blue     14164
22             Dark Azure     13837
31              Dark Pink     12309
208       Trans-Dark Blue     11800
115               Magenta     11640
9                   Brown     10047
204           Trans-Brown      9783
253  [No Color/Any Color]      9452
6     Bright Light Yellow      9069
161           Olive Green      9019
96             Light Aqua      8667
190             Sand Blue      8293
223      Trans-Neon Green      7898
122       Medium Lavender      7276
224     Trans-Neon Orange      6680